apiVersion: v1
kind: Service
metadata:
  name: {{ include "monflask.fullname" . }}
  labels:
    {{- include "monflask.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.flask.servicePort }}
      targetPort: {{ .Values.flask.servicePort }}
      protocol: TCP
      name: flask
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
      protocol: TCP
      name: mongodb
  selector:
    {{- include "monflask.selectorLabels" . | nindent 4 }}

